/* auto-generated by NAPI-RS */
/* eslint-disable */
/** PluresDB database instance for Node.js */
export declare class PluresDatabase {
  /** Create a new PluresDB instance */
  constructor(actorId?: string | undefined | null, dbPath?: string | undefined | null)
  /**
   * Create a PluresDB instance with automatic text embedding.
   *
   * `model` is a HuggingFace model ID such as `"BAAI/bge-small-en-v1.5"`.
   * Every subsequent call to [`put`][PluresDatabase::put] will
   * automatically embed any text content found in the node data.
   *
   * Requires the crate to be compiled with the `embeddings` cargo feature.
   * If the feature is not enabled the method returns an error at runtime.
   *
   * ## JavaScript example
   *
   * ```js
   * const { PluresDatabase } = require('@plures/pluresdb');
   *
   * const db = PluresDatabase.newWithEmbeddings('BAAI/bge-small-en-v1.5');
   * db.put('memory-1', { content: 'user prefers dark mode' });
   * const results = db.vectorSearch([...queryEmbedding], 5, 0.3);
   * ```
   */
  static newWithEmbeddings(model: string, actorId?: string | undefined | null, dbPath?: string | undefined | null): PluresDatabase
  /** Insert or update a node */
  put(id: string, data: any): string
  /** Retrieve a node by ID */
  get(id: string): any | null
  /** Get a node with full metadata (including vector clock and timestamp) */
  getWithMetadata(id: string): any | null
  /** Delete a node by ID */
  delete(id: string): void
  /** List all nodes */
  list(): Array<any>
  /** List nodes filtered by type */
  listByType(nodeType: string): Array<any>
  /**
   * Execute SQL query
   *
   * Requires the `sqlite-compat` cargo feature to be enabled.
   */
  query(sql: string, params?: Array<any> | undefined | null): any
  /**
   * Execute SQL statement (INSERT, UPDATE, DELETE)
   *
   * Requires the `sqlite-compat` cargo feature to be enabled.
   */
  exec(sql: string): any
  /** Search nodes by text content */
  search(query: string, limit?: number | undefined | null): Array<any>
  /**
   * Vector similarity search using a pre-computed embedding.
   *
   * `embedding` must be a flat array of finite floats.  Results are ordered
   * by cosine similarity (highest first) and filtered by `threshold` (0–1).
   */
  vectorSearch(embedding: Array<number>, limit?: number | undefined | null, threshold?: number | undefined | null): Array<any>
  /**
   * Insert or update a node together with its embedding vector.
   *
   * The embedding is indexed immediately so that it is available for
   * subsequent [`vector_search`] calls.
   */
  putWithEmbedding(id: string, data: any, embedding: Array<number>): string
  /**
   * Subscribe to node changes (returns a subscription ID)
   * Note: Full async subscription support requires additional async infrastructure
   */
  subscribe(): string
  /**
   * Embed text using the configured embedding model.
   *
   * Only available when the database was created via `newWithEmbeddings()`.
   * Returns a flat `Vec<f64>` suitable for passing to `vectorSearch()`.
   */
  embed(texts: Array<string>): Array<Array<number>>
  /** Get the embedding dimension, or null if no embedder is configured. */
  embeddingDimension(): number | null
  /** Get the actor ID for this database instance */
  getActorId(): string
  /**
   * Execute a DSL query string against the CRDT store.
   *
   * Returns the procedure result as a JSON object with `nodes`, and
   * optionally `aggregate` or `mutated` fields.
   *
   * # Example (JavaScript)
   *
   * ```js
   * const result = db.execDsl('filter(category == "decision") |> sort(by: "score", dir: "desc") |> limit(10)');
   * console.log(result.nodes);
   * ```
   */
  execDsl(query: string): any
  /**
   * Execute a JSON IR query against the CRDT store.
   *
   * `steps` must be a JSON array of step objects as produced by the
   * pluresdb-procedures builder or parser.
   *
   * # Example (JavaScript)
   *
   * ```js
   * const result = db.execIr([
   *   { op: "filter", predicate: { field: "category", cmp: "==", value: "decision" } },
   *   { op: "limit", n: 5 }
   * ]);
   * ```
   */
  execIr(steps: any): any
  /**
   * Evaluate an [`AgentContext`] against the praxis constraints persisted in
   * the CrdtStore and return every violated constraint.
   *
   * `ctx` is a JSON object `{ action_type, target, session_type, metadata }`
   * that deserializes into the Rust `AgentContext`. Returns a JSON array of
   * `Violation` objects (each with `constraint` and `message`).
   *
   * # Example (JavaScript)
   *
   * ```js
   * const violations = db.pxEvaluate({
   *   action_type: 'write_file',
   *   target: 'config.toml',
   *   session_type: 'main',
   *   metadata: { resource_owner: '' },
   * });
   * ```
   */
  pxEvaluate(ctx: any): any
  /**
   * Pre-action hook: evaluate `ctx` against the CrdtStore-persisted
   * constraints and **block** when any error-severity constraint fires.
   *
   * On a permitted action returns `{ "violations": [...] }` (the warning-only
   * violations, which may be empty). On a blocked action **throws** a JS
   * error carrying the `ActionBlocked` detail, so the Node caller sees a real
   * exception for the block path.
   *
   * # Example (JavaScript)
   *
   * ```js
   * try {
   *   const { violations } = db.pxOnAction({ action_type: 'read_file', target: 'README.md', session_type: 'main', metadata: {} });
   * } catch (err) {
   *   // action was blocked
   * }
   * ```
   */
  pxOnAction(ctx: any): any
  /**
   * Compile a natural-language rule into a [`Constraint`] and **persist** it
   * to the CrdtStore so it is immediately evaluable and survives restart.
   *
   * `text` is the rule description; `id` is the stable constraint ID. Returns
   * the compiled `Constraint` as JSON.
   *
   * # Example (JavaScript)
   *
   * ```js
   * const c = db.pxCompileNl('write_ actions must declare a resource_owner', 'C-OWNER');
   * ```
   */
  pxCompileNl(text: string, id: string): any
  /**
   * Apply a user correction: compile `correction_text` into a constraint
   * (prefixed `[correction]`) and **persist** it to the CrdtStore.
   *
   * Returns a `CorrectionApplied` record (`constraint`, `is_new`,
   * `confirmation`) as JSON. `is_new` reflects whether a constraint with that
   * id already existed as a CrdtStore node.
   *
   * # Example (JavaScript)
   *
   * ```js
   * const applied = db.pxApplyCorrection('risk_score must stay below threshold', 'C-CORR-1');
   * ```
   */
  pxApplyCorrection(correctionText: string, id: string): any
  /**
   * Undo a previously applied correction by deleting its constraint node from
   * the CrdtStore.
   *
   * Returns the removed `Constraint` as JSON, or `null` if no constraint with
   * `constraint_id` exists.
   *
   * # Example (JavaScript)
   *
   * ```js
   * const removed = db.pxUndoCorrection('C-CORR-1'); // Constraint | null
   * ```
   */
  pxUndoCorrection(constraintId: string): any
  /**
   * Query evidence gaps: all `Evidence` records whose result is `Unknown`.
   *
   * Evidence records are not yet persisted as CrdtStore nodes (constraints
   * are the Stage-2 system-of-record scope); the canonical seeded evidence
   * set is read from the default store for gap reporting. Returns a JSON
   * array of `Evidence` objects.
   *
   * # Example (JavaScript)
   *
   * ```js
   * const gaps = db.pxQueryGaps();
   * ```
   */
  pxQueryGaps(): any
  /**
   * Load `.px` source through the **canonical** `pluresdb_px::px::parse`
   * grammar and persist every declared `constraint` block as a CrdtStore
   * node (the single system of record).
   *
   * Each parsed `PxConstraint`'s `require:` expression is compiled to a real
   * enforcing [`Condition`] via the Stage-1 `compile_nl` path (the canonical
   * expression grammar), so a block like `require: amount <= 100` actually
   * blocks `amount = 500`. The declared `severity:` is honored. Returns
   * `{ constraints: [ids...], procedures: [names...] }` describing what was
   * loaded (procedures are reported but not persisted as constraints).
   *
   * # Example (JavaScript)
   *
   * ```js
   * db.pxLoadPxSource('constraint cap:
  require: amount <= 100
  severity: error
  ');
   * ```
   */
  pxLoadPxSource(text: string): any
  /**
   * Insert a single constraint and persist it to the CrdtStore.
   *
   * `constraint` accepts EITHER:
   * - a fully-structured `Constraint` JSON object (`{ id, description, when,
   *   require, fix, evidence, severity }`) — inserted as-is, or
   * - a compile request `{ id, text }` — `text` is compiled to a real
   *   enforcing constraint via the canonical `compile_nl` path.
   *
   * Returns the persisted `Constraint` as JSON.
   *
   * # Example (JavaScript)
   *
   * ```js
   * db.pxInsertConstraint({ id: 'C-CAP', text: 'amount <= 100' });
   * ```
   */
  pxInsertConstraint(constraint: any): any
  /**
   * Build the HNSW vector index from hydrated embeddings.
   * Call after init to enable vector search without blocking startup.
   */
  buildVectorIndex(): number
  /** Get database statistics without loading all nodes into memory. */
  stats(): any
  /**
   * Emit an event into the Agens reactive runtime.
   *
   * The event is persisted as a CRDT node and can be polled by
   * [`agensListEvents`] or dispatched to handlers registered in Rust.
   *
   * `event` must be a JSON object with an `event_type` field (one of:
   * `message`, `timer`, `state_change`, `model_response`, `tool_result`,
   * `praxis_analysis_ready`, `praxis_analysis_failed`,
   * `praxis_guidance_updated`) and the corresponding fields for that type.
   *
   * Returns the CRDT node ID assigned to the event.
   *
   * # Example (JavaScript)
   *
   * ```js
   * const nodeId = db.agensEmit({
   *   event_type: 'message',
   *   id: 'msg-1',
   *   payload: { text: 'hello' },
   * });
   * ```
   */
  agensEmit(event: any): string
  /**
   * Emit a Praxis lifecycle event with **idempotent** storage.
   *
   * Unlike [`agensEmit`], re-emitting the same logical event (same `id`)
   * converges to a single CRDT node rather than creating duplicates.
   *
   * Use for `praxis_analysis_ready`, `praxis_analysis_failed`, and
   * `praxis_guidance_updated` events.
   *
   * Returns the deterministic CRDT node ID (`praxis:cmd:{event_id}`).
   */
  agensEmitPraxis(event: any): string
  /**
   * Poll the Agens command table for events after `sinceIso`.
   *
   * `since_iso` must be an ISO 8601 timestamp (e.g. `"2026-04-05T12:00:00Z"`).
   * Returns events oldest-first as a JSON array.
   *
   * # Performance
   *
   * This method delegates to [`AgensRuntime::poll_events`], which may scan all
   * CRDT nodes via store listing and then filter matching events in memory.
   * As a result, the cost is O(n) in the total store size, including persisted
   * storage, not just in the number of events returned.
   *
   * Avoid high-frequency polling on large stores. Prefer polling on a bounded
   * interval, processing results in batches, and then advancing `since_iso`
   * from the newest processed event timestamp to reduce repeated work.
   *
   * # Example (JavaScript)
   *
   * ```js
   * const events = db.agensListEvents("2026-04-05T00:00:00Z");
   * for (const ev of events) {
   *   console.log(ev.event_type, ev.id);
   * }
   * ```
   */
  agensListEvents(sinceIso: string): Array<any>
  /**
   * Get a value from the Agens reactive state table.
   *
   * Returns `null` if the key is not set.
   */
  agensStateGet(key: string): any
  /**
   * Set a value in the Agens reactive state table.
   *
   * Automatically emits a `state_change` event visible to
   * [`agensListEvents`].
   */
  agensStateSet(key: string, value: any): void
  /**
   * Watch the state table for entries updated since `sinceIso`.
   *
   * Returns an array of `{ key, value }` objects.
   */
  agensStateWatch(sinceIso: string): Array<any>
  /**
   * Schedule a recurring timer in the Agens timer table.
   *
   * Returns the timer node ID (use with [`agensTimerCancel`]).
   */
  agensTimerSchedule(name: string, intervalSecs: number, payload: any): string
  /** Cancel a timer by its ID. Returns `true` if it existed. */
  agensTimerCancel(timerId: string): boolean
  /**
   * List all scheduled timers.
   *
   * Returns an array of `{ id, name, intervalSecs, nextFireAt, payload }`.
   */
  agensTimerList(): Array<any>
  /**
   * Return timers that are due (next_fire_at <= now).
   *
   * Call this in a tick loop to process due timers.
   */
  agensTimerDue(): Array<any>
  /**
   * Reschedule a timer by advancing its next_fire_at by one interval.
   *
   * Returns `true` if the timer existed and was rescheduled.
   */
  agensTimerReschedule(timerId: string): boolean
}

/**
 * Compress a single message/chunk body, routing by content type exactly like
 * the production `compress_one`:
 *
 * * `prose` / `error` → head+tail sentence window (first 3 + `[… N sentences
 *   elided …]` + last 3),
 * * `code` → language-detected signature skeleton,
 * * `log` → consecutive-duplicate run collapse (`line  [×N]`),
 * * `json` / other → whitespace-run squeeze.
 *
 * Preserves the real per-message net-savings guard: the rewrite is returned
 * only when it is actually smaller (in bytes) and non-empty; otherwise the
 * original `content` is returned unchanged. Bodies under 200 chars pass
 * through untouched. `contentType`, when provided, pins the route the TS seam
 * already knows; otherwise the real detector classifies the content.
 *
 * This never fabricates a ratio and never paraphrases — the output is always a
 * smaller-or-equal, byte-derived transform of the SAME content.
 *
 * ## JavaScript example
 *
 * ```js
 * const { compressText } = require('@plures/pluresdb');
 * const compact = compressText(longChunk);                 // auto-detect
 * const code    = compressText(src, { contentType: 'code' }); // pin route
 * ```
 */
export declare function compressText(content: string, contentType?: string | undefined | null): string

/**
 * Count tokens in `text` using the real `tiktoken_rs::cl100k_base` tokenizer
 * (the same tokenizer pares-agens uses), with the BPE tables cached process-
 * wide so repeated calls do not reallocate. Returns the exact cl100k token
 * count — the canonical metric for compression-ratio reporting.
 *
 * ## JavaScript example
 *
 * ```js
 * const { countTokens } = require('@plures/pluresdb');
 * const ratio = countTokens(compact) / countTokens(original);
 * ```
 */
export declare function countTokens(text: string): number

/**
 * Detect the content type of `content`, returning one of
 * `"json" | "log" | "code" | "error" | "prose"`. Port of the real
 * `detect_content_type` actor (structural heuristics, not just keywords).
 *
 * ## JavaScript example
 *
 * ```js
 * const { detectContentType } = require('@plures/pluresdb');
 * const kind = detectContentType(chunk); // 'code' | 'log' | ...
 * ```
 */
export declare function detectContentType(content: string): string

/** Initialize the module */
export declare function init(): void
